"""Add admissions table

Revision ID: 7f980cfe80d4
Revises: e17966775086
Create Date: 2026-04-30 04:15:46.984798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f980cfe80d4'
down_revision: Union[str, None] = 'e17966775086'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('previous_school', sa.String(), nullable=False),
    sa.Column('marks_obtained', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', name='admissionstatus'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admissions_email'), 'admissions', ['email'], unique=False)
    op.create_index(op.f('ix_admissions_id'), 'admissions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admissions_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_email'), table_name='admissions')
    op.drop_table('admissions')
    # ### end Alembic commands ###
