"""Update schema for events and admissions

Revision ID: e17966775086
Revises: 5362de8738d5
Create Date: 2026-04-30 04:15:06.676038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e17966775086'
down_revision: Union[str, None] = '5362de8738d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('location', sa.String(), nullable=True))
    op.add_column('events', sa.Column('image_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'image_url')
    op.drop_column('events', 'location')
    # ### end Alembic commands ###
